# Generated by Django 5.0.2 on 2024-02-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=1, upload_to='events'),
            preserve_default=False,
        ),
    ]
