# Generated by Django 5.0.2 on 2024-04-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_event_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
