# Generated by Django 5.0.2 on 2024-02-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='image',
            field=models.ImageField(default=1, upload_to='speaker'),
            preserve_default=False,
        ),
    ]
